### ISSUE TITLE
SHA2-512 HMAC one-liner fails to compile.

### ISSUE THREAD

**Issue by kayabaNerve** [cheatfate/nimcrypto#27] opened 2019-05-30 05:01 UTC
```
import nimcrypto
discard sha512.hmac("", "")
```

```
SHA2.nim(52, 11) template/generic instantiation of `hmac` from here
~/.nimble/pkgs/nimcrypto-0.3.9/nimcrypto/hmac.nim(287, 8) template/generic instantiation of `init` from here
~/.nimble/pkgs/nimcrypto-0.3.9/nimcrypto/hmac.nim(139, 26) Error: ambiguous call; both hmac.sizeBlock(h: HMAC[sizeBlock.RipemdContext]) [declared in ../../../../../.nimble/pkgs/nimcrypto-0.3.9/nimcrypto/hmac.nim(78, 10)] and hmac.sizeBlock(h: HMAC[sizeBlock.Sha1Context]) [declared in ../../../../../.nimble/pkgs/nimcrypto-0.3.9/nimcrypto/hmac.nim(105, 10)] match for: (HMAC[sha2.sha512])
```

**Comment by cheatfate** [comment] 2019-05-31 12:48
Sorry but it looks like some regression inside of latest Nim devel.

**Comment by kayabaNerve** [comment] 2019-05-31 16:39
Ah. That would make sense as I recently recompiled. Sorry.

**Comment by cheatfate** [comment] 2019-06-01 18:11
https://github.com/nim-lang/Nim/issues/11375

**Comment by cheatfate** [comment] 2019-06-02 06:48
Fixed in Nim devel with https://github.com/nim-lang/Nim/commit/4a35d2b571190e94e151091535793cd033b589b1

**Closed by cheatfate** 2019-06-02 06:48 UTC
